# Generated by Django 3.2.3 on 2021-07-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=60, verbose_name='фамилия')),
                ('login', models.CharField(max_length=40, verbose_name='логин')),
                ('name', models.CharField(max_length=60, verbose_name='имя')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='changed',
            field=models.DateField(auto_now=True, null=True, verbose_name='изменен'),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='создан'),
        ),
        migrations.AddField(
            model_name='post',
            name='if_published',
            field=models.BooleanField(default=False, verbose_name='опубликован ли'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(default='new post', max_length=60, verbose_name='имя поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='website.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default='tag', max_length=40, unique=True, verbose_name='имя тега'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, verbose_name='имя категории'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=120, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.author', verbose_name='автор'),
        ),
    ]
